djangoProject1/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='course-list'),
    path('<int:pk>/',views.CourseDetailView.as_view(), name ='course-detail'),
    path('update/<int:pk>', views.CourseUpdateView.as_view(), name='course-update'),
    path('delete/<int:pk>/',views.CourseDeleteView.as_view(), name='course-delete'),
    path('create/', views.CourseCreateView.as_view(), name='course-create'),

]

djangoProject1/djangoProject1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('home.urls')),
    path('courses/', include('courses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

djangoProject1/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),

]

djangoProject1/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout', views.logout_view, name='logout'),
    path('register/', views.registration_view, name='registration'),
    path('login/', views.login_user_view, name='login'),

]

djangoProject1/templates/partials/message.html
{% if messages %}
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

djangoProject1/templates/partials/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home:home' %}">
        <img class="logo" src="{% static 'images/logo.svg' %}" alt="Logo LMS">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'courses:course-list' %}">Courses</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'courses:course-create' %}">Create</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:contact' %}">Contact</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="">{{user.fullname}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:registration' %}">Register</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>