djangoProject1/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='course-list'),
    path('<int:pk>/',views.CourseDetailView.as_view(), name ='course-detail'),
    path('update/<int:pk>', views.CourseUpdateView.as_view(), name='course-update'),
    path('delete/<int:pk>/',views.CourseDeleteView.as_view(), name='course-delete'),
    path('create/', views.CourseCreateView.as_view(), name='course-create'),

]

djangoProject1/djangoProject1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', include('home.urls')),
    path('courses/', include('courses.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

djangoProject1/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),

]

djangoProject1/courses/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models
from django.utils.text import slugify
from django.contrib.contenttypes.models import ContentType
# Create your models here.


class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)

    def __str__(self):
        return  self.title

    class Meta:
        ordering = ('title',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Course(models.Model):
    title = models.CharField(max_length=200)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,related_name='courses_creator')
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE, related_name='courses')
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    overview = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(get_user_model(), related_name='courses_students')
    course_image = models.ImageField(upload_to='courses')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created_at',)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class Module(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, default='')
    course = models.ForeignKey('Course', on_delete=models.CASCADE, related_name='modules')

    def __str__(self):
        return self.title


class Content(models.Model):
    module = models.ForeignKey('Module', on_delete=models.CASCADE, related_name='contents')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, limit_choices_to={
        'models__in':('text', 'video', 'image', 'file')
    })
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type','object_id')





class ItemBase(models.Model):
    owner = models.ForeignKey(get_user_model(),on_delete=models.CASCADE, related_name='%(class)s_related')
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Text(ItemBase):
    content = models.TextField()


class Video(ItemBase):
    content = models.URLField()


class File(ItemBase):
    content = models.FileField(upload_to='files')


class Image(ItemBase):
    content = models.ImageField(upload_to='images')

djangoProject1/courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from . import models
from django.urls import reverse_lazy, reverse

from .permissions import OwnerRequiredMixin


# Create your views here.
class CourseListView(ListView):
    model = models.Course
    template_name = 'courses/course_list.html'
    context_object_name = 'courses'

class CourseDetailView(DetailView):
    model = models.Course
    template_name = 'courses/course_details.html'
    context_object_name = 'course'

class CourseUpdateView(LoginRequiredMixin, OwnerRequiredMixin,UpdateView):
    model = models.Course
    fields = ('title', 'slug', 'subject', 'overview')
    template_name = 'courses/course_create.html'
    login_url = reverse_lazy('users:login')


    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse('courses:course-detail', kwargs={'pk': pk})

    #def form_valid(self, form):

class CourseDeleteView(LoginRequiredMixin, OwnerRequiredMixin, DeleteView):
    model = models.Course
    template_name = 'courses/course_delete.html'
    context_object_name = 'course'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('courses:course-list')

class CourseCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Course
    fields = ('title','slug','subject','course_image')
    template_name = 'courses/course_create.html'
    success_url = reverse_lazy('courses:course-list')
    login_url = reverse_lazy('users:login')
    permission_required = 'courses.add_course'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

djangoProject1/courses/templates/courses/course_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create/Update</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-warning" type="submit">Submit</button>

    </form>
{% endblock %}

djangoProject1/courses/templates/courses/course_delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'courses:course-delete' pk=course.pk %}" method="post">
        {% csrf_token %}
        <h2 class="text-center mt-3">Are you sure you want to delete <b>{{ course }}</b></h2>
        <div class="d-flex justify-content-center">
            <a class="btn btn-success btn-lg m-3" href="{% url 'courses:course-detail' pk=course.pk %}">Cancel</a>
            <button class="btn btn-danger  btn-lg m-3" type="submit">Confirm</button>
        </div>
    </form>
{% endblock %}

djangoProject1/courses/templates/courses/course_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-3 col-md-offset-2">
            <img src="{{ course.course_image.url }}" alt="{{ course.title }}" class="img-thumbnail">
        </div>
        <div class="col-md-9">
            <h1>{{ course.title }}</h1>
            <p><i>Created by: {{ course.owner }} at {{ course.created_at }}</i></p>
            <p class="lead my-3">{{ course.overview }}</p>
        {% if user.is_authenticated %}
            {% if user.id == course.owner.id %}
                <a href="{%  url 'courses:course-update' pk=course.id %}" class="btn btn-danger">Edit Course</a>
                <a href="{% url 'courses:course-delete' pk=course.id %}" class="btn btn-danger">Delete Course</a>
            {% else %}
                {% if user in course.students.all %}
                    <a href="" class="btn btn-success">View Course</a>
                {% else %}
                    <a href="" class="btn btn-warning">Take this course</a>
                {% endif %}
            {% endif %}
        {% endif %}
        </div>
    </div>
{% endblock %}

djangoProject1/courses/templates/courses/course_list.html
{%  extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <div class="card-group">
                {%  for course in courses %}
                    <div class="card mb-3 me-3" style = "max-width: 18rem;">
                        <img src="{{ course.course_image.url }}" alt="{{ course.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ course.title }}</h5>
                            <p class="card-text">{{ course.overview }}</p>
                            <a href="{% url 'courses:course-detail' pk=course.id %}" class="btn btn-primary">See course</a></div>
                    </div>
                {% empty %}
                    <h2>No course found</h2>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}